version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prodhub_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=prodhub_db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: ./backend # Tells it to find the Dockerfile in the 'backend' folder
    command: gunicorn product_importer.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app # Mounts your code
    ports:
      - "8000:8000" # Exposes port 8000 to your EC2 instance
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db # <-- This is the "magic". It uses the service name 'db'
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis # <-- Uses the service name 'redis'
      - REDIS_PORT=6379
      - DEBUG=False
      - ALLOWED_HOST=* # Be more specific in production!
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: ./backend
    command: celery -A product_importer worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - DEBUG=False
      - ALLOWED_HOST=*
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data: # This volume makes your database data "persist"