version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prodhub_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=prodhub_db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: . 
    command: gunicorn product_importer.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/app # Mounts the current folder to /app
    ports:
      - "8000:8000" 
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db 
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis # <-- Uses the service name 'redis'
      - REDIS_PORT=6379
      - DEBUG=False
      - ALLOWED_HOST=*
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: . 
    command: celery -A product_importer worker --loglevel=info
    volumes:
      - .:/app # Mounts the current folder to /app
    environment:
      - RDS_DB_NAME=prodhub_db
      - RDS_USERNAME=prodhub_user
      - RDS_PASSWORD=mysecretpassword
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - DEBUG=False
      - ALLOWED_HOST=*
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data: # This volume makes your database data "persist"